In [ ]:
import numpy as np 
import pandas as pd
import seaborn as sns 
import  matplotlib.pyplot as plt 


In [4]:
testing_data= pd.read_csv("Testing.csv")
training_data = pd.read_csv("Training.csv")


In [10]:
training_data.head()
training_data.drop("Unnamed: 133",axis = 1)

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,(vertigo) Paroymsal Positional Vertigo
4916,0,1,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,Acne
4917,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Urinary tract infection
4918,0,1,0,0,0,0,1,0,0,0,...,0,0,1,1,1,1,0,0,0,Psoriasis


In [12]:
training_data.info
testing_data.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
2,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,GERD
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Chronic cholestasis
4,1,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Drug Reaction


In [17]:
training_data= pd.DataFrame(training_data)
testing_data = pd.DataFrame(testing_data)
data = pd.concat([training_data,testing_data])

In [31]:
new_data= data.drop("Unnamed: 133",axis =1)
new_data.shape
print(list(new_data.columns))

['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing', 'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity', 'ulcers_on_tongue', 'muscle_wasting', 'vomiting', 'burning_micturition', 'spotting_ urination', 'fatigue', 'weight_gain', 'anxiety', 'cold_hands_and_feets', 'mood_swings', 'weight_loss', 'restlessness', 'lethargy', 'patches_in_throat', 'irregular_sugar_level', 'cough', 'high_fever', 'sunken_eyes', 'breathlessness', 'sweating', 'dehydration', 'indigestion', 'headache', 'yellowish_skin', 'dark_urine', 'nausea', 'loss_of_appetite', 'pain_behind_the_eyes', 'back_pain', 'constipation', 'abdominal_pain', 'diarrhoea', 'mild_fever', 'yellow_urine', 'yellowing_of_eyes', 'acute_liver_failure', 'fluid_overload', 'swelling_of_stomach', 'swelled_lymph_nodes', 'malaise', 'blurred_and_distorted_vision', 'phlegm', 'throat_irritation', 'redness_of_eyes', 'sinus_pressure', 'runny_nose', 'congestion', 'chest_pain', 'weakness_in_limbs', 'fast_heart_rate', 'pain_during_bow

In [43]:
features = ["chest_pain","breathlessness","sweating" , "fast_heart_rate","fatigue" , "dizziness" ,"increased_appetite","obesity" ,"irritability" , "polyuria" ,"watering_from_eyes" , "chills",
           "continuous_sneezing","joint_pain","stomach_pain","muscle_wasting","weight_gain","weight_loss","lethargy","irregular_sugar_level",
           "high_fever","dehydration","nausea","malaise","blurred_and_distorted_vision","runny_nose","muscle_weakness","unsteadiness","bladder_discomfort",
           "muscle_pain","family_history","prognosis","vomiting","anxiety","restlessness","cough","sunken_eyes","sweating",
           "diarrhoea","loss_of_appetite","throat_irritation","redness_of_eyes","congestion","weakness_in_limbs","visual_disturbances"]

In [46]:
updated_data =new_data[features]

In [47]:
updated_data

,chest_pain,breathlessness,sweating,fast_heart_rate,fatigue,dizziness,increased_appetite,obesity,irritability,polyuria,...,cough,sunken_eyes,sweating,diarrhoea,loss_of_appetite,throat_irritation,redness_of_eyes,congestion,weakness_in_limbs,visual_disturbances
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [48]:
updated_data.isnull().sum()

chest_pain                      0
breathlessness                  0
sweating                        0
fast_heart_rate                 0
fatigue                         0
dizziness                       0
increased_appetite              0
obesity                         0
irritability                    0
polyuria                        0
watering_from_eyes              0
chills                          0
continuous_sneezing             0
joint_pain                      0
stomach_pain                    0
muscle_wasting                  0
weight_gain                     0
weight_loss                     0
lethargy                        0
irregular_sugar_level           0
high_fever                      0
dehydration                     0
nausea                          0
malaise                         0
blurred_and_distorted_vision    0
runny_nose                      0
muscle_weakness                 0
unsteadiness                    0
bladder_discomfort              0
muscle_pain   

In [49]:
X = updated_data.drop("prognosis",axis =1 )
Y = updated_data["prognosis"]

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
X_train , X_test , y_train , y_test = train_test_split(
    X , Y , test_size = 0.28,random_state = 512)

In [54]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=None, min_samples_split=2,
                               min_samples_leaf=1,
                               min_weight_fraction_leaf=0.0, max_features='sqrt', max_leaf_nodes=None, min_impurity_decrease=0.0,
                               bootstrap=True, oob_score=False, n_jobs=None, random_state=None, verbose=0, 
                               warm_start=False, class_weight=None, ccp_alpha=0.0, max_samples=None, monotonic_cst=None)

In [55]:
model.fit(X_train , y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [56]:
y_pred = model.predict(X_test)

In [57]:
y_pred

array(['Heart attack', 'Peptic ulcer diseae', 'GERD', ..., 'hepatitis A',
       'Chicken pox', 'Hepatitis D'], shape=(1390,), dtype=object)

In [58]:
print(list(y_pred))

['Heart attack', 'Peptic ulcer diseae', 'GERD', 'Acne', 'AIDS', 'Alcoholic hepatitis', 'Tuberculosis', 'Hepatitis D', 'hepatitis A', 'Migraine', 'Hypoglycemia', 'Peptic ulcer diseae', 'Tuberculosis', 'Alcoholic hepatitis', 'Bronchial Asthma', 'Allergy', 'hepatitis A', 'Pneumonia', 'Acne', 'Gastroenteritis', '(vertigo) Paroymsal  Positional Vertigo', 'Acne', 'Dengue', 'AIDS', 'Chicken pox', 'Hyperthyroidism', 'Typhoid', 'Hypoglycemia', 'Acne', 'Peptic ulcer diseae', 'Alcoholic hepatitis', 'Varicose veins', '(vertigo) Paroymsal  Positional Vertigo', 'Tuberculosis', 'Pneumonia', 'Arthritis', 'Common Cold', 'hepatitis A', 'Diabetes ', 'Alcoholic hepatitis', 'Peptic ulcer diseae', 'Migraine', 'Common Cold', '(vertigo) Paroymsal  Positional Vertigo', 'Osteoarthristis', 'AIDS', 'hepatitis A', 'Chicken pox', 'hepatitis A', 'Varicose veins', 'Allergy', 'Alcoholic hepatitis', 'Osteoarthristis', 'Acne', 'Hypertension ', 'Acne', 'Hepatitis E', 'Hypothyroidism', 'Impetigo', 'Common Cold', 'Drug Rea

In [59]:
y_true = y_test

In [68]:
from sklearn.metrics import accuracy_score , precision_score , recall_score , f1_score ,confusion_matrix,classification_report

print("Accuracy:", accuracy_score(y_true, y_pred))
# print("Precision:", precision_score(y_true, y_pred , average='binary'))
# print("Recall:", recall_score(y_true, y_pred))
# print("F1-Score:", f1_score(y_true, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))
# print(classification_report(y_true, y_pred, target_names=['Class 0', 'Class 1']))

Accuracy: 0.8733812949640288
Confusion Matrix:
 [[34  0  0 ...  0  0  0]
 [ 0 27  0 ...  0  0  0]
 [ 0  0 34 ...  0  0  0]
 ...
 [ 0  0  4 ... 36  0  0]
 [ 0  0  0 ...  0 34  0]
 [ 0  0  0 ...  0  0 36]]


In [76]:
model.predict([[1,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0]])

C:\Users\singh\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array(['Diabetes '], dtype=object)